### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by Puterboy1** [Nenkai/GTToolsSharp#7]
I'm trying to extract the files of GT5,VOL and I get this error: 

public static readonly Keyset Keyset_PFS_DEFAULT = new Keyset("PFS_DEFAULT", "PDIPFSDEFAULT", new Key(0x04C11DB7, 0x04C11DB7, 0x04C11DB7, 0x04C11DB7));
public static readonly Keyset Keyset_GT5P_SPEC2_US_PSN = new Keyset("GT5P_SPEC2_US_PSN", "SONORA-550937027", new Key(0xFD7F0A4B, 0x6DE31FCD, 0xB5B14A50, 0x2F174A36));
public static readonly Keyset Keyset_GT5P_US_SPEC_III = new Keyset("GT5P_US_SPEC_III", "SONORA-550937027", new Key(0x4B0A7FFD, 0xCD1FE36D, 0x504AB1B5, 0x364A172F));
public static readonly Keyset Keyset_GT5P_EU_SPEC_III = new Keyset("GT5P_EU_SPEC_III", "TOTTORI-562314254", new Key(0x5F29A71B, 0xA80945CF, 0xBECCA74F, 0x07C9800F));
public static readonly Keyset Keyset_GT5P_CITROEN = new Keyset("GT5P_CITROEN", "KARAKUM-176730298", new Key(0x995515F1, 0xC7BA38EF, 0xA9837BE5, 0x60C4925F));
public static readonly Keyset Keyset_GT5_TIME_TRIAL_CHALLENGE_HK = new Keyset("GT5_TIME_TRIAL_CHALLENGE_HK", "ORDOS-29082919", new Key(0x33B41763, 0xB737084B, 0xD039E95F, 0xA42AF29B));
public static readonly Keyset Keyset_GT5_TIME_TRIAL_CHALLENG_US = new Keyset("GT5_TIME_TRIAL_CHALLENG_US", "CARCROSS-85963023", new Key(0x7C90C351, 0x53D1057D, 0x358FA239, 0xF50932BF));
public static readonly Keyset Keyset_GT5_TIME_TRIAL_CHALLENG_EU = new Keyset("GT5_TIME_TRIAL_CHALLENG_EU", "PISCINAS-77828733", new Key(0xDC110915, 0xAC7D03BD, 0xA694AF0D, 0x91E83CF1));
public static readonly Keyset Keyset_GT5_KIOSK_DEMO = new Keyset("GT5_KIOSK_DEMO", "ARABIAN-312107402", new Key(0x3036F45D, 0xD134AB3F, 0x859A665B, 0x16F82F9D));
public static readonly Keyset Keyset_GT5_EU = new Keyset("GT5_EU", "KALAHARI-37863889", new Key(0x2DEE26A7, 0x412D99F5, 0x883C94E9, 0x0F1A7069));
public static readonly Keyset Keyset_GT5_US = new Keyset("GT5_US", "PATAGONIAN-22798263", new Key(0x5A1A59E5, 0x4D3546AB, 0xF30AF68B, 0x89F08D0D));
public static readonly Keyset Keyset_GT5_JP = new Keyset("GT5_JP", "SAHARA-568201135", new Key(0xD770A27B, 0x2114AABD, 0xDD8C423D, 0x54690651));
public static readonly Keyset Keyset_GT_ACADEMY_2012_EU = new Keyset("GT_ACADEMY_2012_EU", "GREATBASIN-579805832", new Key(0xE631DC25, 0x82C2998F, 0x4F875673, 0xBD641F33));
public static readonly Keyset Keyset_GT_ACADEMY_2012_US = new Keyset("GT_ACADEMY_2012_US", "CHIHUAHUAN-638729911", new Key(0x8128DD09, 0xA82AB067, 0x49DBA01F, 0x499939D3));
public static readonly Keyset Keyset_GT_ACADEMY_2012_ASIA = new Keyset("GT_ACADEMY_2012_ASIA", "GREATSANDY-774795678", new Key(0x95878E3F, 0xC58426A1, 0x72E21421, 0x1D3CC8FB));
public static readonly Keyset Keyset_GT5_ASIA = new Keyset("GT5_ASIA", "TAKLAMAKAN-63706075", new Key(0x93783D89, 0x33D56FB5, 0xE7701B43, 0x6032AD93));
public static readonly Keyset Keyset_GT6_ACADEMY_2013 = new Keyset("GT6_ACADEMY_2013", "CHOLISTAN-901501638", new Key(0x98D2BDC1, 0x0968F1C5, 0xC857640B, 0xAEB52EF5));
public static readonly Keyset Keyset_GT6 = new Keyset("GT6", "PISCINAS-323419048", new Key(0xAA1B6A59, 0xE70B6FB3, 0x62DC6095, 0x6A594A25));
[X] Could not unpack volume. Make sure that you have a valid game key/seed in your key.json.
Exiting.

**Comment by Puterboy1** [comment]
I figured out the keys, but now I am getting this: Error: Unable to parse key.json. '0' is an invalid start of a property name. Expected a '"'. Path: $[9].Key | LineNumber: 121 | BytePositionInLine: 13.
Exiting.

HELP!!!

**Comment by Nenkai** [comment]
Improper usage.
The tool must be run once to create the keys file, and another time to unpack.

**Comment by Puterboy1** [comment]
[key.zip](https://github.com/Nenkai/GTToolsSharp/files/11012395/key.zip)
This is my Key file. I put the keys in and....could you give me one that will actually work?

**Comment by Puterboy1** [comment]
This is the command I used: C:\Users\jaker>C:\Users\jaker\Downloads\GTToolsSharp.exe\GTToolsSharp.exe unpack -i "C:\Users\jaker\Downloads\Gran Turismo 5\PS3_GAME\USRDIR\GT.VOL" -o "C:\Users\jaker\Downloads\Gran Turismo 5\PS3_GAME\USRDIR"
-- GTToolsSharp 5.2.0 - (c) Nenkai#9075, ported from flatz's gttool --

Error: Unable to parse key.json. '0' is an invalid start of a property name. Expected a '"'. Path: $[10].Key | LineNumber: 134 | BytePositionInLine: 12.
Exiting.

**Comment by ddm999** [comment]
Delete your messed up key file, run the program once and it will make a working key file. Then re-run it and it'll work. You don't need to edit the key file at all.

**Comment by Puterboy1** [comment]
I have deleted the key.

**Comment by Puterboy1** [comment]
But whenever I start the .exe it just disappears instantly, even when I run it as administrator. As my computer is an HP Omen, it has a tendency to do that. Would it be just easier if you sent me a key.json?

**Comment by ddm999** [comment]
Run it from command line, exactly as you were doing before, but without your broken keyfile.
Any command line tool needs to be run from the command line.

**Comment by Puterboy1** [comment]
I am doing that. And then after it gets the no verb selected thing, I don't see a key popping up.

**Comment by Puterboy1** [comment]
C:\Users\jaker>C:\Users\jaker\Downloads\GTToolsSharp.exe\GTToolsSharp.exe
-- GTToolsSharp 5.2.0 - (c) Nenkai#9075, ported from flatz's gttool --

GTToolsSharp 5.1.0
Copyright (C) 2023 GTToolsSharp

ERROR(S):
  No verb selected.

  pack               Packs a volume file.

  unpack             Unpacks a volume file.

  unpackinstaller    Unpacks an installation file (TV.DAT)

  crypt              Decrypts/Encrypts a general game file (mostly from the user data folder on the console).

  cryptsalsa         Decrypts/Encrypts a file using a specified Salsa20 key. Normally used for the database files
                     (specdb, menudb, caption.dat)

  cryptmovie         Decrypt the specified Salsa20 key, then decrypts the provided movie file. Keys for each movie file
                     are within menudb.

  listfiles          List all volume entries into a file.

  compress           Custom compresses a file (also known as PS2ZIP)

  gt7unpack          Unpacks a GT7 volume file.

  help               Display more information on a specific command.

  version            Display version information.

Exiting.

**Comment by ddm999** [comment]
Run that command you wrote before.
This one:

> C:\Users\jaker\Downloads\GTToolsSharp.exe\GTToolsSharp.exe unpack -i "C:\Users\jaker\Downloads\Gran Turismo 5\PS3_GAME\USRDIR\GT.VOL" -o "C:\Users\jaker\Downloads\Gran Turismo 5\PS3_GAME\USRDIR"

It will say

> [X] Error: Volume Encryption Key file is missing (key.json).
>  A default one was created with the keys for the following game codes:
> ...

plus more stuff

and then run the exact command again
and it will work

**Comment by Puterboy1** [comment]
I did it, but all I got was this: public static readonly Keyset Keyset_PFS_DEFAULT = new Keyset("PFS_DEFAULT", "PDIPFSDEFAULT", new Key(0x04C11DB7, 0x04C11DB7, 0x04C11DB7, 0x04C11DB7));
public static readonly Keyset Keyset_GT5P_SPEC2_US_PSN = new Keyset("GT5P_SPEC2_US_PSN", "SONORA-550937027", new Key(0xFD7F0A4B, 0x6DE31FCD, 0xB5B14A50, 0x2F174A36));
public static readonly Keyset Keyset_GT5P_US_SPEC_III = new Keyset("GT5P_US_SPEC_III", "SONORA-550937027", new Key(0x4B0A7FFD, 0xCD1FE36D, 0x504AB1B5, 0x364A172F));
public static readonly Keyset Keyset_GT5P_EU_SPEC_III = new Keyset("GT5P_EU_SPEC_III", "TOTTORI-562314254", new Key(0x5F29A71B, 0xA80945CF, 0xBECCA74F, 0x07C9800F));
public static readonly Keyset Keyset_GT5P_CITROEN = new Keyset("GT5P_CITROEN", "KARAKUM-176730298", new Key(0x995515F1, 0xC7BA38EF, 0xA9837BE5, 0x60C4925F));
public static readonly Keyset Keyset_GT5_TIME_TRIAL_CHALLENGE_HK = new Keyset("GT5_TIME_TRIAL_CHALLENGE_HK", "ORDOS-29082919", new Key(0x33B41763, 0xB737084B, 0xD039E95F, 0xA42AF29B));
public static readonly Keyset Keyset_GT5_TIME_TRIAL_CHALLENG_US = new Keyset("GT5_TIME_TRIAL_CHALLENG_US", "CARCROSS-85963023", new Key(0x7C90C351, 0x53D1057D, 0x358FA239, 0xF50932BF));
public static readonly Keyset Keyset_GT5_TIME_TRIAL_CHALLENG_EU = new Keyset("GT5_TIME_TRIAL_CHALLENG_EU", "PISCINAS-77828733", new Key(0xDC110915, 0xAC7D03BD, 0xA694AF0D, 0x91E83CF1));
public static readonly Keyset Keyset_GT5_KIOSK_DEMO = new Keyset("GT5_KIOSK_DEMO", "ARABIAN-312107402", new Key(0x3036F45D, 0xD134AB3F, 0x859A665B, 0x16F82F9D));
public static readonly Keyset Keyset_GT5_EU = new Keyset("GT5_EU", "KALAHARI-37863889", new Key(0x2DEE26A7, 0x412D99F5, 0x883C94E9, 0x0F1A7069));
public static readonly Keyset Keyset_GT5_US = new Keyset("GT5_US", "PATAGONIAN-22798263", new Key(0x5A1A59E5, 0x4D3546AB, 0xF30AF68B, 0x89F08D0D));
public static readonly Keyset Keyset_GT5_JP = new Keyset("GT5_JP", "SAHARA-568201135", new Key(0xD770A27B, 0x2114AABD, 0xDD8C423D, 0x54690651));
public static readonly Keyset Keyset_GT_ACADEMY_2012_EU = new Keyset("GT_ACADEMY_2012_EU", "GREATBASIN-579805832", new Key(0xE631DC25, 0x82C2998F, 0x4F875673, 0xBD641F33));
public static readonly Keyset Keyset_GT_ACADEMY_2012_US = new Keyset("GT_ACADEMY_2012_US", "CHIHUAHUAN-638729911", new Key(0x8128DD09, 0xA82AB067, 0x49DBA01F, 0x499939D3));
public static readonly Keyset Keyset_GT_ACADEMY_2012_ASIA = new Keyset("GT_ACADEMY_2012_ASIA", "GREATSANDY-774795678", new Key(0x95878E3F, 0xC58426A1, 0x72E21421, 0x1D3CC8FB));
public static readonly Keyset Keyset_GT5_ASIA = new Keyset("GT5_ASIA", "TAKLAMAKAN-63706075", new Key(0x93783D89, 0x33D56FB5, 0xE7701B43, 0x6032AD93));
public static readonly Keyset Keyset_GT6_ACADEMY_2013 = new Keyset("GT6_ACADEMY_2013", "CHOLISTAN-901501638", new Key(0x98D2BDC1, 0x0968F1C5, 0xC857640B, 0xAEB52EF5));
public static readonly Keyset Keyset_GT6 = new Keyset("GT6", "PISCINAS-323419048", new Key(0xAA1B6A59, 0xE70B6FB3, 0x62DC6095, 0x6A594A25));
[X] Could not unpack volume. Make sure that you have a valid game key/seed in your key.json.
Exiting.

**Comment by Puterboy1** [comment]
There are no keys in it either: "GameCode": "GT5_US",
    "Magic": "PATAGONIAN-22798263",
    "Key": {
      "Data": [
        1511676389,
        1295337131,
        4077581963,
        2314243341
      ]
    },
    "DecryptManager": null

**Comment by ddm999** [comment]
The numbers after Data **_are_** the keys. They're just in decimal, not the hexadecimal that you're seeing.

What version of GT5 is this? Do you know the product code for it (something like BCUS98114)?

**Comment by Puterboy1** [comment]
I don't.

**Comment by Puterboy1** [comment]
I got it from here: https://ps3.psgamedl.com/Gran%20Turismo%205%20(USA)%20(EnJaFrEsPt)%20(v02.00).zip

**Comment by Puterboy1** [comment]
https://romspure.cc/download/gran-turismo-5-20516
